### ISSUE TITLE
[protonj2] Handle `amqp:connection:forced` remote close and reconnect cleanly

### ISSUE THREAD

**Issue by jiridanek** [rh-messaging/cli-java#451]
https://issues.apache.org/jira/browse/PROTON-2618

```
[15:38:33] [FAIL] dtestlib.Test :: [root@10.88.0.3]$ /opt/miniconda3/envs/tn/bin/python3 -u /var/dtests/node_data/clients/cli_wrapper.py  -DDTESTS_PID=1013960 -DC_KILLTIME=240 -DC_HANG_ANALYSIS_ENA=0 -DC_CRASH_ANALYSIS_ENA=0 -DC_CRASH_FILE_DELETE_ENA=0  java  -jar /var/dtests/node_data/clients/protonj2.jar receiver  --timeout 120 --log-msgs dict --broker 10.88.0.3:5672 --conn-reconnect True --conn-auth-mechanisms PLAIN --conn-username admin --conn-password admin --address "test_client_reconnect_msgsrv_sigterm" --count 1 # ecode:1 (exp. True), dur.:10.56 err_cnt:1
[15:38:33] [INFO] dtestlib.Test :: stderr:
  org.apache.qpid.protonj2.client.exceptions.ClientConnectionRemotelyClosedException: Received error from remote peer without description [condition = amqp:connection:forced]
  	at org.apache.qpid.protonj2.client.impl.ClientExceptionSupport.convertToConnectionClosedException(ClientExceptionSupport.java:128)
  	at org.apache.qpid.protonj2.client.impl.ClientLinkType.handleParentEndpointClosed(ClientLinkType.java:378)
  	at org.apache.qpid.protonj2.engine.impl.ProtonLink.fireParentEndpointClosed(ProtonLink.java:517)
  	at org.apache.qpid.protonj2.engine.impl.ProtonLink.handleConnectionLocallyClosed(ProtonLink.java:590)
  	at org.apache.qpid.protonj2.engine.impl.ProtonSession.lambda$handleConnectionLocallyClosed$1(ProtonSession.java:467)
  	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
  	at org.apache.qpid.protonj2.engine.impl.ProtonSession.handleConnectionLocallyClosed(ProtonSession.java:467)
  	at org.apache.qpid.protonj2.engine.impl.ProtonConnection.lambda$close$0(ProtonConnection.java:144)
  	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
  	at org.apache.qpid.protonj2.engine.impl.ProtonConnection.close(ProtonConnection.java:144)
  	at org.apache.qpid.protonj2.engine.impl.ProtonConnection.close(ProtonConnection.java:63)
  	at org.apache.qpid.protonj2.client.impl.ClientConnection.handleRemoteClose(ClientConnection.java:694)
  	at org.apache.qpid.protonj2.engine.impl.ProtonEndpoint.fireRemoteClose(ProtonEndpoint.java:139)
  	at org.apache.qpid.protonj2.engine.impl.ProtonConnection.handleClose(ProtonConnection.java:449)
  	at org.apache.qpid.protonj2.engine.impl.ProtonPerformativeHandler.handleClose(ProtonPerformativeHandler.java:158)
  	at org.apache.qpid.protonj2.engine.impl.ProtonPerformativeHandler.handleClose(ProtonPerformativeHandler.java:43)
  	at org.apache.qpid.protonj2.types.transport.Close.invoke(Close.java:74)
  	at org.apache.qpid.protonj2.engine.IncomingAMQPEnvelope.invoke(IncomingAMQPEnvelope.java:69)
  	at org.apache.qpid.protonj2.engine.impl.ProtonPerformativeHandler.handleRead(ProtonPerformativeHandler.java:68)
  	at org.apache.qpid.protonj2.engine.impl.ProtonEngineHandlerContext.invokeHandlerRead(ProtonEngineHandlerContext.java:187)
  	at org.apache.qpid.protonj2.engine.impl.ProtonEngineHandlerContext.fireRead(ProtonEngineHandlerContext.java:147)
  	at org.apache.qpid.protonj2.engine.impl.ProtonFrameLoggingHandler.handleRead(ProtonFrameLoggingHandler.java:101)
  	at org.apache.qpid.protonj2.engine.impl.ProtonEngineHandlerContext.invokeHandlerRead(ProtonEngineHandlerContext.java:187)
  	at org.apache.qpid.protonj2.engine.impl.ProtonEngineHandlerContext.fireRead(ProtonEngineHandlerContext.java:147)
  	at org.apache.qpid.protonj2.engine.impl.ProtonFrameDecodingHandler$FrameBodyParsingStage.parse(ProtonFrameDecodingHandler.java:363)
  	at org.apache.qpid.protonj2.engine.impl.ProtonFrameDecodingHandler$FrameSizeParsingStage.parse(ProtonFrameDecodingHandler.java:259)
  	at org.apache.qpid.protonj2.engine.impl.ProtonFrameDecodingHandler.handleRead(ProtonFrameDecodingHandler.java:99)
  	at org.apache.qpid.protonj2.engine.impl.ProtonEngineHandlerContext.invokeHandlerRead(ProtonEngineHandlerContext.java:199)
  	at org.apache.qpid.protonj2.engine.impl.ProtonEngineHandlerContext.fireRead(ProtonEngineHandlerContext.java:132)
  	at org.apache.qpid.protonj2.engine.impl.ProtonEnginePipeline.fireRead(ProtonEnginePipeline.java:301)
  	at org.apache.qpid.protonj2.engine.impl.ProtonEngine.ingest(ProtonEngine.java:227)
  	at org.apache.qpid.protonj2.engine.impl.ProtonEngine.ingest(ProtonEngine.java:53)
  	at org.apache.qpid.protonj2.client.impl.ClientTransportListener.transportRead(ClientTransportListener.java:59)
  	at org.apache.qpid.protonj2.client.transport.TcpTransport$NettyTcpTransportHandler.channelRead0(TcpTransport.java:481)
  	at org.apache.qpid.protonj2.client.transport.TcpTransport$NettyTcpTransportHandler.channelRead0(TcpTransport.java:471)
```

**Comment by jiridanek** [comment]
Currently, JAMQConnectioniiiTests/test_client_reconnect_msgsrv_sigterm fails due to this

**Comment by jiridanek** [comment]
* https://issues.apache.org/jira/browse/QPIDJMS-563
