### ISSUE TITLE
Selftests failing on timeout when closing artemis-jms client

### ISSUE THREAD

**Issue by jiridanek** [rh-messaging/cli-java#482]
https://github.com/rh-messaging/cli-java/actions/runs/3343717290/jobs/5538377440#step:7:28746

```
Caused by: org.junit.jupiter.api.AssertTimeoutPreemptively$ExecutionTimeoutException: Execution timed out in thread junit-timeout-thread-1
	at java.base/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2211)
	at org.apache.activemq.artemis.core.protocol.core.impl.ChannelImpl.sendBlocking(ChannelImpl.java:518)
	at org.apache.activemq.artemis.core.protocol.core.impl.ChannelImpl.sendBlocking(ChannelImpl.java:446)
	at org.apache.activemq.artemis.core.protocol.core.impl.ActiveMQSessionContext.sessionClose(ActiveMQSessionContext.java:622)
	at org.apache.activemq.artemis.core.client.impl.ClientSessionImpl.close(ClientSessionImpl.java:1342)
	at org.apache.activemq.artemis.jms.client.ActiveMQSession.close(ActiveMQSession.java:323)
	at com.redhat.mqe.lib.CoreClient.close(CoreClient.java:338)
	at com.redhat.mqe.lib.CoreClient.closeConnObjects(CoreClient.java:306)
	at com.redhat.mqe.acc.AccSenderClient.startClient(AccSenderClient.java:161)
	at com.redhat.mqe.lib.Main.main(Main.java:46)
	at com.redhat.mqe.acc.Main.main(Main.java:85)
	at AccMainTest.main_(MainTest.kt:146)
	at AbstractMainTest.main(AbstractMainTest.kt:79)
	at AbstractMainTest.main(AbstractMainTest.kt:74)
	at AbstractMainTest.sendBrowseAndReceiveSingleMessageWithNonemptySelector$lambda$6(AbstractMainTest.kt:226)
	at org.junit.jupiter.api.AssertTimeoutPreemptively.lambda$assertTimeoutPreemptively$0(AssertTimeoutPreemptively.java:48)
	at org.junit.jupiter.api.AssertTimeoutPreemptively.lambda$submitTask$3(AssertTimeoutPreemptively.java:95)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

Try upgrading https://github.com/jiridanek/docker-alpine-openjdk-artemis-snapshot to more recent versions of software and latest Artemis broker.

**Comment by jiridanek** [comment]
https://github.com/jiridanek/docker-alpine-openjdk-artemis-snapshot/commit/9fd0339a5234aa704fc1c02598c341e274f3a58b

https://quay.io/repository/jdanek/docker-alpine-openjdk-artemis-snapshot/build/51efa264-6831-424d-a503-85f779fdc12f

**Comment by jiridanek** [comment]
quay-hosted build failed, will build locally and push it on quay
