### ISSUE TITLE
[cli-protonj2] --broker does not default to ampq port on localhost

### ISSUE THREAD

**Issue by jiridanek** [rh-messaging/cli-java#488]
```
$ java -jar "${cli_protonj2}" sender --address cli-qpid-jms --log-msgs dict --count 1
Connection ID:b63f49d8-16fe-4a5d-93b5-bac2ecbf1962:1:1 has failed due to: ClientConnectionRemotelyClosedException -> MD5: Name or service not known
org.apache.qpid.protonj2.client.exceptions.ClientConnectionRemotelyClosedException: MD5: Name or service not known
        at org.apache.qpid.protonj2.client.impl.ClientExceptionSupport.convertToConnectionClosedException(ClientExceptionSupport.java:157)
        at org.apache.qpid.protonj2.client.impl.ClientTransportListener.transportError(ClientTransportListener.java:74)
        at org.apache.qpid.protonj2.client.transport.TcpTransport.handleTransportFailure(TcpTransport.java:342)
        at org.apache.qpid.protonj2.client.transport.TcpTransport$NettyDefaultHandler.exceptionCaught(TcpTransport.java:465)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
        at io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:69)
        at io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:65)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
        at org.apache.qpid.protonj2.client.transport.TcpTransport.connect(TcpTransport.java:149)
        at org.apache.qpid.protonj2.client.transport.TcpTransport.connect(TcpTransport.java:56)
        at org.apache.qpid.protonj2.client.impl.ClientConnection.attemptConnection(ClientConnection.java:968)
        at org.apache.qpid.protonj2.client.impl.ClientConnection.lambda$scheduleReconnect$17(ClientConnection.java:987)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.UnknownHostException: MD5: Name or service not known
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1529)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1519)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1377)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1305)
        at java.base/java.net.InetAddress.getByName(InetAddress.java:1255)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
        at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:162)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:123)
        ... 11 more
```

What is MD5???

**Comment by jiridanek** [comment]
```java
    @CommandLine.Option(names = {"-b", "--broker"}, description = "MD5, SHA-1, SHA-256, ...")
    private String broker = "MD5";
```

LOL, heh, 🤦🏽
