### ISSUE TITLE
amqx NullPointerException: Cannot invoke "java.lang.Throwable.toString()" because the return value of "java.lang.Throwable.getCause()" is null

### ISSUE THREAD

**Issue by jiridanek** [rh-messaging/cli-java#558]
https://github.com/rh-messaging/cli-java/blob/52ed86e8027efb9242931d996d26486600ffdf64/cli-activemq-jmx/src/main/java/com/redhat/amqx/management/ObjectReader.java#L99-L106

```
[13:12:00] [FAIL] dtestlib.Test :: [root@10.0.202.30]$ /opt/miniconda3/envs/tn/bin/python3 -u /var/dtests/node_data/clients/cli_wrapper.py  -DDTESTS_PID=5477 -DC_KILLTIME=60 -DC_HANG_ANALYSIS_ENA=0 -DC_CRASH_ANALYSIS_ENA=0 -DC_CRASH_FILE_DELETE_ENA=0  java  -jar /var/dtests/node_data/clients/amqx.jar  queue --host 10.0.202.30:1099 --username admin --password admin --action properties --name 'test_receive_ttl_message_in_half_life' # ecode:254 (exp. True), dur.:1.07 err_cnt:4
[13:12:00] [INFO] dtestlib.Test :: stdout:
  Unable to properties queue: Cannot invoke "java.lang.Throwable.toString()" because the return value of "java.lang.Throwable.getCause()" is null
  java.lang.NullPointerException: Cannot invoke "java.lang.Throwable.toString()" because the return value of "java.lang.Throwable.getCause()" is null
  	at com.redhat.amqx.management.ObjectReader.extractMethodProperty(ObjectReader.java:103)
  	at com.redhat.amqx.management.ObjectReader.getObjectProperties(ObjectReader.java:165)
  	at com.redhat.amqx.management.artemis.AbstractArtemisManager.getDestinationProperties(AbstractArtemisManager.java:180)
  	at com.redhat.amqx.management.artemis.DestinationArtemisManager.getDestinationProperties(DestinationArtemisManager.java:138)
  	at com.redhat.amqx.main.actions.QueueAction.run(QueueAction.java:107)
  	at com.redhat.amqx.main.Main.main(Main.java:52)
```

Some throwables don't have a cause.

**Comment by jiridanek** [comment]
And, the author of the change seems to be @clebertsuconic, who changed the type of the return value of `getNumberOfPages` from int to long in https://github.com/apache/activemq-artemis/pull/4101, https://github.com/apache/activemq-artemis/commit/342565d4c1475e974c5cf874ad419842f037e976#diff-0d4c38e316b8b8defd6ef45ef5a40f402fc4ec5673d4b3756887aea161ef2246L101-R101 and since we are compiling against an older Artemis (we happen to use artemis-core-client-2.20.0.redhat-00008.jar) which has still an int type in the interface, we fail like that.
