### ISSUE TITLE
java.lang.NullPointerException at com.redhat.mqe.CliProtonJ2Sender.performMessageSending(CliProtonJ2Sender.java:252)

### ISSUE THREAD

**Issue by jiridanek** [rh-messaging/cli-java#582]
This is a flaky failure

https://github.com/rh-messaging/cli-java/blob/6fb568a72f76222f392050efcb2e47b5dfa29367/cli-protonj2/src/main/java/com/redhat/mqe/CliProtonJ2Sender.java#L246-L264

```
[13:27:15] [FAIL] dtestlib.Test :: [root@10.0.202.24]$ /opt/miniconda3/envs/tn/bin/python3 -u /var/dtests/node_data/clients/cli_wrapper.py  -DDTESTS_PID=47178 -DC_KILLTIME=200 -DC_HANG_ANALYSIS_ENA=0 -DC_CRASH_ANALYSIS_ENA=0 -DC_CRASH_FILE_DELETE_ENA=0  java  -jar /var/dtests/node_data/clients/protonj2.jar sender  --log-msgs interop --broker 10.0.202.24:5672 --conn-auth-mechanisms PLAIN --conn-username admin --conn-password admin --address "test_transaction_sender_batch_size_leftovers_bigger" --count 400 --tx-size 30 --tx-action commit # ecode:1 (exp. 0), dur.:1.58 err_cnt:1
[13:27:15] [INFO] dtestlib.Test :: stderr:
  java.lang.NullPointerException
  	at com.redhat.mqe.CliProtonJ2Sender.performMessageSending(CliProtonJ2Sender.java:252)
  	at com.redhat.mqe.CliProtonJ2Sender.call(CliProtonJ2Sender.java:214)
  	at com.redhat.mqe.CliProtonJ2Sender.call(CliProtonJ2Sender.java:43)
  	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
  	at picocli.CommandLine.access$1500(CommandLine.java:148)
  	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
  	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
  	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
  	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
  	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
  	at picocli.CommandLine.execute(CommandLine.java:2170)
  	at com.redhat.mqe.Main.main(Main.java:35)
```

**Comment by jiridanek** [comment]
@tabish121 I only saw this once, but, how is it possible that `tracker.remoteState()` can be `null` after I do `tracker.awaitSettlement()`?

This is sending in a transaction, btw.

**Comment by tabish121** [comment]
Remote state can be null if the remote didn't apply an outcome to the disposition and only marked it as settled which is valid behavior although not very helpful.

**Comment by tabish121** [comment]
I believe I've tracked down the issue that allows the settlement future to trip to soon which is why you sometimes see a null outcome, I'm working on a fix.

**Comment by jiridanek** [comment]
@tabish121 Thanks, I tired with 1.0.0-M14-SNAPSHOT and I haven't seen the issue again in 100+ runs, so I think https://issues.apache.org/jira/browse/PROTON-2705 really did resolve it.
