### ISSUE TITLE
  Unable to remove queue: Failed to retrieve RMIServer stub: javax.naming.NameNotFoundException: jmxrmi

### ISSUE THREAD

**Issue by jiridanek** [rh-messaging/cli-java#662]
```
$ /opt/miniconda3/envs/tn/bin/python3 -u /var/dtests/node_data/clients/cli_wrapper.py  -DDTESTS_PID=4374 -DC_KILLTIME=60 -DC_HANG_ANALYSIS_ENA=0 -DC_CRASH_ANALYSIS_ENA=0 -DC_CRASH_FILE_DELETE_ENA=0  java  -jar /var/dtests/node_data/clients/amqx.jar  queue --host 10.0.141.157:1099 --username admin --password admin --action remove --name 'test_direct_transient_text_message' # ecode:255 (exp. True), dur.:0.56 err_cnt:1
[19:00:32] [INFO] dtestlib.Test :: stdout:
  Unable to remove queue: Failed to retrieve RMIServer stub: javax.naming.NameNotFoundException: jmxrmi
  java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.NameNotFoundException: jmxrmi
  	at java.management.rmi/javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:370)
  	at java.management/javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
  	at com.redhat.amqx.management.AbstractConnectionManager.<init>(AbstractConnectionManager.java:54)
  	at com.redhat.amqx.management.artemis.AbstractArtemisManager.<init>(AbstractArtemisManager.java:36)
  	at com.redhat.amqx.management.artemis.DestinationArtemisManager.<init>(DestinationArtemisManager.java:22)
  	at com.redhat.amqx.management.ManagerFactory.createDestinationManager(ManagerFactory.java:145)
  	at com.redhat.amqx.main.actions.QueueAction.run(QueueAction.java:91)
  	at com.redhat.amqx.main.Main.main(Main.java:52)
  Caused by: javax.naming.NameNotFoundException: jmxrmi
  	at jdk.naming.rmi/com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136)
  	at java.naming/com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:220)
  	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
  	at java.management.rmi/javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1839)
  	at java.management.rmi/javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1813)
  	at java.management.rmi/javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:302)
  	... 7 more
```

**Comment by jiridanek** [comment]
https://issues.redhat.com/browse/RHEL-2144
